title: Kritisk Computer Oplysning
description: Fordi IT ikke er en forkortelse for idioti

url: https://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Forside
    url: /index.html
  - title: Om
    url: /about
  - title: Kontakt
    url: /contact

#social:
#  github: brianmaierjr
#  twitter: brianmaierjr
#  facebook: brianmaierjr
#  email: brimaidesigns@gmail.com
#  linkedin: brianmaierjr

#google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
